export const intro1 = "Perhaps being one of the more fun assignments during my time in university, this assignment really allowed me to step out of the box and attempt to express my creativity in a visual way. In my first glance at the brief, I was immediately reminded of the 3 phase story structure that I learnt while preparing for my internship interviews (set-up → build-up → climax). Immediately after reading the brief, besides the 3 phase structure, I also figured the story should have other aspects like engagement, emotion and suspense to capture the viewer's attention. I wanted to transcend just the assignment alone, into something that a viewer might actually enjoy.";
export const intro2 = "The initial stories I thought of included a rivalry between two spotlights in my room (inspired by the Pixar lamp), as they try to one-up each other. However, coincidentally, I was eating instant noodles while reading the brief, and had the idea of some kind of story using the multiple flavors of instant noodles that I enjoy.";
export const intro3 = "Personally preferring the pink Samyang ramen I was eating over the yellow ones in my shelf, I figured: “what if the yellow noodles were jealous?” - which served as the perfect arc for the story!";
export const intro4 = "Inspired by this arc, I decided to have a conclusive and violent ending to this story about jealousy, where the yellow bowl knocks the pink bowl out, and takes its place.";

// storyboarding
export const process1 = "Due to the ruthless limit on the number of frames, the storyboard had to be concise enough to communicate the complete story within a few shots. This implied that each slide/scene had to be atomic in nature (i.e. only communicate a singular independent idea that other slides do not). I initially came up with a storyboard but realize the technical and emotive limitations, to eventually create another one based on it. An iPad was used for all storyboards.";
export const process2 = "I also had to consider the practicality of a scene in the context of photography. This not only includes the basics such as the possibility of angles and styles, but also encapsulates how lighting, focus and other elements can be leveraged to strongly express ideas. The final storyboard was designed around getting the maximum out of the photos, by using heuristics based on my previous experiences to figure out how to convey the following aspects:";
export const process3 = "I also had the ramen bowls in mind before designing the storyboard, as I wanted to exploit every ounce of design from the physical bowls themselves - and found that the illustrated characters on the bowls themselves serve as the perfect manifestation of the intended emotions in this story.";

// photography
export const process4 = "After a solid foundation had been created using storyboarding, it was time for photography. Having composition, color scheme and flow in mind, I tried placing and testing scenes around my house using the noodle bowls - abiding mostly to the storyboard slides but also experimenting different angles, as photograph results differ from sketches due to aspects like depth, colors, size and more.";
export const process5 = "In terms of composition, I learnt a lot from lectures regarding the framing of subjects. Likewise, most frames have either the rule of thirds or centering to create harmony and focus respectively. The second last image is an exception, where dissonance and disharmony are created to show movement and unrest, supplemented by a highly unnatural angle.";
export const process6 = "Continuing from the previous points about emotion, I also experimented with lighting to further show malicious intent, jealousy and motives of the yellow bowl in the 6th frame. I was surprised by how much of a difference lighting originally made when interpreting the pictures in terms of the conveyed emotions. Learning from this specific slide, I will certainly keep lighting in mind for any future multimedia storytelling or film projects.";
export const process7 = 'Another way lighting was used was subtle shadows and focus spotlights using soft make-shift diffusers made with pillow-cases and my table spotlight. For instance, artificial shadows were induced by focusing the lights on the background instead of the foreground for images 4 and 5, to convey that the pink bowl is metaphorically “in the dark” about the intentions of the yellow bowl.';
export const process8 = "The evaluation of which images were shortlisted and subsequently selected were done mostly in context of their position within the 9 frames, and their relationships or flow with the frames around them. This made me realize how important it is to evaluate all frames as a whole, as some of the pictures were good independently, but not in conjunction with other frames (this was further reinforced after the critique).";

// adobe
export const process9 = "Prior to framing, I realized the images needed to be adjusted on Photoshop slightly to enforce a consistent color grading across all images. Only needing minor edits on 3 images, this was easily done on photoshop using the Curves tool to compensate for mismatching white-balances while shooting under different conditions. This further increased my appreciation and encouraged me to control my conditions before shooting in the future.";
export const process10 = "Another idea that intrigued me in taking the scenes to the next level was the notion of “selective emphasis”. Taking inspiration from manga and superhero comic books, an interesting idea was to selectively crop and size scenes based on its importance. This was particularly important for slide 6 compared to the first 3, where the first 3 were less important as they were purely setting up the story, while the 6th was a turning point in the plot, where the intent of the yellow bowl was fully revealed. To achieve this, a slight slant is introduced with the framing, to increase surface area for image 6 by eating into the first 3.";
export const process11 = "The vertical borders between the 3 rows of images were also varied to clearly separate the story by each of the 3 acts, as each row appears more atomic and separate as opposed to if the borders lined up with each other for the case of a perfect 3x3 grid.";
export const process12 = "To fit images into the grid, the clipping mask feature was used in Illustrator to easily fit images to shapes created using the rectangular tool and adjusted to fit the edits described above.";

export const critique1 = "The critique for this assignment included two inputs from my peers and the tutor: (a) make the background less blur for image 4 to let the viewer know that the yellow bowl is in the background; and (b) perhaps include the yellow bowl in the first frame.";
export const critique2 = "The first input was quite obvious once pointed out - as the primary issue was that it wasn't instantly clear if images 4 and 5 were related - when in reality it was the same perspective with different focuses for different ideas. While taking a new image of image 4 with a smaller aperture for less blur, I realized the same problem existed with image 5, where it's impossible to tell that the foreground is the pink bowl. Working on this particular input made me learn more about how to establish a mental model of the set in the minds of the viewer effectively, through subtle visual queues. ";
export const critique3 = "The second input was perhaps more important than I realized, as it really helped cement the idea that the person consciously made the decision to choose the pink bowl instead of the yellow bowl - strengthening the motive behind the arc of revenge seen later. Agreeing with the point, I decided to include the yellow bowl on the shelf in image 1.";

export const learning1 = "Overall, the challenge of conveying a cohesive and complete story within 6-9 frames certainly enabled me to think of storytelling in a more structural way. It definitely allowed me to realize the co-dependence between the various phases too. Transcendent beyond this assignment, this assignment further cemented how I'd express anything through any medium through individual ideas that are relate to each other to create a cohesive meaning. Examples include:";
export const learning2 = "Continuing from the techniques carried out in this assignment, I definitely expect to leverage the various aspects of photography that I've exploited in this assignment to express ideas in the future, and use storyboarding as an essential tool for planning storytelling through a visual medium like film and photography. I also hope to continue this level of brainstorming and experimentation with anything creative that I do in the future.";