export const intro1 = "Coming into this assignment without much experience in graphic design, my expectations with regards to abstraction were originally about the reduction of some graphical medium. However, after working on this assignment, I'd like to think of abstraction more as the extraction of certain ideas from a subject, instead of purely a form of reduction.";
export const intro2 = "To explore how I can extract ideas from a photograph or a visual medium, I decided to do this assignment on my backpack - as I felt an item I had used for years would make it easier for me to extract ideas from it.";

export const stage01 = "The benefit of using a bag is certainly the ease of taking its picture in your room, but I was wondering also how to compose the image better. I originally had the intention of exploring some form of semiotics with a flat design language for the final stage, so I decided to take a centered picture of the bag directly from the front.";
export const stage02 = 'Due to the not-so-white walls of my room, I had to extract the bag to make it easier for me to trace it in stage 1. To do this, I could leverage the “Subject” feature in Photoshop to extract the bag from its background.';

export const stage11 = "Getting as much detail as possible, I decided to spend a lot of time tracing the bag with contours and shapes for the most prevalent shades of the bag using the pen and curvature tools Illustrator. Starting from the darkest shade for the base, I decided to work my way through the bag using incremental shades of brightness. Due to my intuition that the ribbon serves as an identifying symbol for this bag specifically, I decided to keep the colors of the ribbon close to the original.";
export const stage12 = "Due to the flat nature of filled color shapes in illustrator, I realized that finer details cannot be replicated in an accurate way (eg. the zips, buckles etc.). To compensate for this weakness with shapes, I attempted to replicate the “feel” of these finer details using larger shapes. From this step, I noticed that the bag doesn't look realistic when zoomed in, but looks very realistic zoomed out.";
export const stage13 = "To stage the image before tracing it, I converted the extracted subject image into greyscale using the “convert to greyscale” option in Illustrator due to the slight bluish tint of the bag. This further implied that I could use a color picker to fill shapes while tracing, instead of needing to guess what color it is - and still manage to generate shapes in black and white.";

export const stage21 = "Due to the significant extent of detail for the first stage, the target for this stage was to reduce detail and abstract towards some basic shapes instead of a highly detailed “feel” of the bag using rough shapes. Firstly, to reduce the detail in terms of the shades of stage 1, the brightest layer of colored shapes were removed, and the curves were simplified both manually and with the simplify tool in Illustrator.";
export const stage22 = "To simplify details with regards to other features present in stage 1, I realized that some objects can be removed further - if they don't contribute heavily to signifying the bag. To achieve this, the ribbon was simplified heavily, and some straps and buckles were removed completely as well. ";
export const stage23 = "Being one of the inputs received in the critique, originally the distance from stage 1 to stage 2 was significantly lesser than stage 2 to stage 3. To smoothen the flow from stage 1 to stage 3, I further edited stage 2 to align it closer with stage 3. From a visual perspective, although the steps above were enough to differentiate step 1 from step 2 from a technical standpoint, it wasn't enough in a subjective or human-perceptive standpoint due to the negligible differences in overall shape of the bag. This results in people feeling that step 1 and 2 are near identical on first glance. Since step 3 is about symmetry, I attempted to further edit the overall shape of step 2 to get closer to step 3.";

export const stage31 = "Perhaps one of the more striking jumps in design language, this stage first and foremost tries to insert a higher degree of symmetry into the overall shape of the bag, as at this point I figured I'd want to get closer to a form of semiotics using a flat icon in the last stage. This therefore further allowed me to solidify the vision I had for this assignment.";
export const stage32 = "In the first step of making the bag symmetric, I inserted a make-shift box to use as a guideline to structure the bag with regards to its overall shape. This provided the much needed symmetry in the outlines of the bag as well.";
export const stage33 = "However, I realized that the insides were highly asymmetric due to the leaning lines and creases that the bag had, as well as the asymmetric opening of the lid in stage 2. To combat this issue, I replaced significant amount of shading from the right side to match with the left side, and added some more synthetic lines instead of realistic ones, to converge at some level of graphical reduction in terms of the fidelity of the shapes.";

export const stage41 = "The good thing about this stage was that the previous stage solidified an approach towards some kind of flat symbol, so I knew exactly what to do at this point. The first thing I did was reducing shades significantly to form more clearer lines - to a higher extent than the previous stage. This further meant removing any organic shapes from the image of the bag to abide by a more flat design language. ";
export const stage42 = "The symmetry of the figure was further taken to an extreme, making the canvas perfectly symmetric with the exception of the ribbon and the tag at the bottom right. I kept the ribbon in this stage for identification of the bag but tried to make it a bit more geometric to abide by the symmetric and flat design language.";
export const stage43 = "Other changes at this stage were the removal of all the buckles because their high-fidelity look contradicted the low-fidelity design language of this stage.";

export const stage51 = "The final stage was about reducing the dimensionality of the figure from 3D to 2D completely, to achieve the flat look I desired to make the figure a clear symbol for the specific bag. To achieve this, all shades were removed to create uniformity in the figure, including making the lines implicit through white space. This further helped paint the figure as a cohesive - and most importantly, singular - object, instead of one figure having multiple sub-objects as seen in stage 4. The lines were further redone to make the widths of all lines identical.";
export const stage52 = "Other changes from stage 4 included the uniformity in visual hierarchy in this stage. In stage 4, the bright ribbon and the different shades established a clear linear visual hierarchy. The ribbon was therefore reduced to a white outline of where the ribbon should be, as it adequately and effectively conveyed the feeling of identification with regards to the original bag.";
export const stage53 = "I also originally intended to remove the tag on the bottom right, but it provided the needed offset in visual weight to counter the weight created by the ribbon on the left side. But I made it a flat rectangle to ensure the consistency in design language.";
export const stage54 = "To further play around with the ideas I learnt from the lectures, I decided to use the golden ratio between the length of the ribbon, and the height from the bottom of the lid to the bottom of the bag.";
export const stage5c = "Thank you Curie for bringing up a valid point during the critique session about the original figure appearing to be more of a laptop case rather than a bag. Following from our discussion, I decided to make the lid wider to be consistent with the original bag, as laptop cases don't often have wide lids but bags often do. I also added a more rectangular lid rather than the highly curved lid in the original symbol. Someone also mentioned that the lines were uneven so I smoothened the lines too.";

export const conclusion = "Through this assignment as well as the critique sessions, I learnt a lot about how to extract an idea from a subject using a graphical medium. Being an oil painter with experience in abstraction through my paintings, it was particularly hard for me to achieve the last stage as previously with my paintings it was more about the diversity of interpretations a work of art can have - while in graphic design the perceived idea has to be common across all viewers as a form of truth.";




