export const intro1 = "This project might have been the most fun in this module so far - perhaps getting me a bit obsessed about making the perfect infographic.";
export const intro2 = "The brief induced an explosion of ideas in my mind, including infographics about wormholes, music, mobile phones, types of rice and computers. However, while deciding on a topic, I realized that I had built a hobbyist mechanical keyboard a few weeks ago - after doing in-depth research about how to build one. Deciding to go with this topic, I wanted to give the audience an idea about how to build a keyboard with essential parts and important information.";
export const intro3 = "Previously having a background in user experience design, the brief immediately reminded me of certain UX information principles upon first reading it. Therefore topics such as hierarchy, cognitive load, visual context, and information architecture provided some valuable initial direction when working on this assignment later down the line. Besides these UX-related topics, I further had the following aspects in mind when approaching the brief:";

export const brain1 = "Choosing the right information had its challenges, but it was done mostly on an essential basis to the subject topic of building a mechanical keyboard. It included the 4 essential parts of a keyboard: keycaps, switches, PCB and case, as well as some extra information about layouts, stabilizers and lubrication. Although the extra information didn't necessarily belong to a singular part of a keyboard, they were needed to build a mechanical keyboard from scratch.";
export const brain2 = "The next plan of action was to determine a style of storytelling or a general flow to the whole infographic. Being stuck on this dilemma for a while, I eventually thought about decomposing the keyboard parts like a hamburger, and putting extra information on the sides with different visual queues in terms of color, white-space and positioning for clear differentiation in the reader's flow. The parts of the keyboard then needed to be ordered in the way they're constructed, to make it user friendly for the user to follow. The level of complexity had to also be approachable (rather than necessarily reduced), as I assumed any viewer that might potentially view the infographic wouldn't necessarily be accustomed to the knowledge and customs of mechanical keyboard.";
export const brain3 = "Using the “hamburger” decomposition idea further, I had a few ideas on how to represent a decomposed keyboard on screen. This included a messy representation, a horizontally symmetric split, or an isometrically 3D decomposition. Using sketches to prototype these ideas, I realized that a messy representation would be difficult to follow due to visual noise, and a horizontal split might not be visually engaging enough to the viewer. An isometric design would give some structure to a 3d plane, making the keyboard come alive in a satisfying way. All assets were also drawn by hand at first to get a rough idea on their appearance, and to guide the tracing process in latter phases.";
export const brain4 = "I further wanted to exploit an engaging color scheme to keep the viewer's eyes engaged with the infographic, while reducing cognitive load at the same time through selectively grabbing and directing attention through the specific areas of the infographic. To achieve this, an overall flat neon color scheme with a contrasting color scheme of blue and orange for core items was selected to gain attention. I further played around with other color coded areas like hot pink titles for instance, to grab the reader's attention to the parts of the keyboard before moving to extra information. Experimenting with leveraging popular mental models for objects, I wanted to immediately let the user know what a certain item was based on its color - an instance is the deviation from orange to make the PCB green, as mental models for circuit boards include a green color for the silicon which houses the circuits.";

export const proc1 = "Following the planning stage, all assets and objects were created on Illustrator using the Pen tool. I tried looking for references images, but could not find any in the isometric angle I was creating this project. So most assets were hand-drawn first, then traced directly on screenshots of the hand-drawn objects. For some rough reference, I used my own keyboard to get an idea of the proportions and angles. I heavily used some guiding lines in illustrator to help keep a consistent isometric angle for all objects.";
export const proc2 = "Some assets were simply too complex or detailed due to size constraints or inconsistencies in overall design language - especially since a lot of the isometric objects were abstracted by default to some extent. These assets had to be abstracted even further, to achieve the consistent flat look I desired for the entire infographic.";
export const proc3 = "At all parts of the process, the consistency of a uniform design language was always in mind - as every object had to follow the same angular and color philosophy as seen in the brainstorming process. This permeated through tracing, composition, backgrounds, texts.";
export const proc4 = "Speaking of texts, I figured sans-serif text would be needed for this project to convey a casual tone for a casual subject. However, I did spend some time experimenting with different sans-serif fonts such as Roboto, Lato, Myriad Pro, Helvetica, Futura and Noto Sans. These are the characteristics I picked up from these fonts when experimenting:";
export const proc5 = "These characters eventually led me to shortlisting Noto Sans and Lato, due to their emphasis for functional user friendliness and general perceived modernity, as well as certain modern characteristics. However, I eventually went with Lato due to its uniqueness and perceived inviting warmth.";

export const crit1 = "The few inputs received in the critique session were very useful in refining the infographic further. One of these inputs were about the font sizes being too small to be easily readable. Originally having the small font sizes due to the idea of making the infographic a larger scale poster, I did agree with this point - as digitally they did appear a bit small. To combat this, I tried experimenting with increasing the font size a few points to find a sweet spot - to eventually arrive at the font size of 8 pt, as the size of 9 pt created visual noise which in-turn caused cognitive overload.";
export const crit2 = "Another input was about the flow and differentiation between the different sections on the infographic, with someone pointing out that for instance it's not clear to follow from keycaps to switches instead of keycaps to stabilizers for instance. To combat this issue, header colors were changed for the extra information to better contrast with the parts of the keyboard. Originally orange, these headers were too close to the pink headers for parts. I therefore changed these headers to a shade of cool temperature blue to better contrast with the warm pink.";
export const crit3 = "Subtle but effective guiding arrows were added to the headers which point to specific parts of the keyboard to create an explicit link between a content section and a graphical depiction of a part of a keyboard. Besides guiding the user, this further was done to differentiate between the information about the parts of the keyboard and the extra sections further (as the extra section headers do not have these guiding arrows).";
export const crit4 = "I also had an idea to leverage Gestalt grouping principles to make sub-sections in the infographic more atomic in nature. Achieved by encapsulating sub-sections in translucent white rectangles, it helped these sections stand out as singular objects instead of fragmented text separated by white-spacing. The sub-header rectangles were also removed to reduce visual noise further. Overall, this took the infographic at a whole new level, making it highly structured and user friendly.";
export const crit5 = "Someone mentioned that the history section was irrelevant to the subject topic of “how to build a keyboard”. Agreeing with this, I also found out that the history section had to be removed to create space for font size increases, Gestalt grouping and adequate white-space between sections. It also reduced visual noise to make the audience focus on the information that was directly relevant to the subject matter instead.";

export const other1 = "Besides the inputs critique, I further edited the infographic based on my thoughts after the critique session. These included adding atmospheric objects to create the vibe of constructing a keyboard from scratch (including switches and a screwdriver lying around in the background).";
export const other2 = "I also added some gradient shaded boxes below the graph curves for the switches to be more consistent with the overall design language of solid shapes over solid strokes present throughout the infographic. This also increased the visibility of the graph curves significantly, helping the viewer spot and understand them to a further extent.";

export const refl1 = "This assignment made me critically reflect on how information should be planned, structured and executed in an engaging way to the audience through a graphical medium. Taking what I learnt to the future, I wish to continue practicing what I learnt here across all visual mediums relevant to my field such as UI/UX design, frontend engineering and graphic design.";
export const refl2 = "It also taught me how to make things prettier, which was nice.";
